// Supabase Edge Function: generate-release-notes
//
// DUMMY worker for now: it validates the request, returns 202 immediately, and
// does the slow work in the background (EdgeRuntime.waitUntil) so neither this
// request nor the user's web request blocks for 30s. After the delay it writes
// the generated markdown to Storage and flips the release_notes row to 'draft'.
//
// TODO(real generation): replace the delay + buildDummyMarkdown with
//   1. fetch the tag range via GitHub (compare / generate-notes) using installationId
//   2. summarise via the Anthropic API
//
// Run locally:  supabase functions serve generate-release-notes
// Deploy:       supabase functions deploy generate-release-notes
// (verify_jwt defaults to true, so the caller's user JWT is required.)

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

declare const EdgeRuntime: { waitUntil(promise: Promise<unknown>): void };

type GeneratePayload = {
  releaseNoteId: string;
  repositoryFullName: string;
  owner: string;
  repo: string;
  installationId: number;
  startTag: string;
  endTag: string;
  storagePath: string;
};

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!;

const DUMMY_DELAY_MS = 30_000;

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' }
  });

function buildDummyMarkdown(payload: GeneratePayload): string {
  return [
    `# ${payload.repositoryFullName} ${payload.endTag}`,
    '',
    `_Release notes generated from ${payload.startTag} to ${payload.endTag}._`,
    '',
    '## ✨ Features',
    '- _Placeholder feature summary (dummy worker)._',
    '',
    '## 🐛 Fixes',
    '- _Placeholder fix summary (dummy worker)._',
    '',
    '---',
    '> Generated by the ShipLog dummy worker. Real GitHub + AI generation coming soon.',
    ''
  ].join('\n');
}

async function runGeneration(payload: GeneratePayload, userId: string) {
  const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

  try {
    // Simulate the cost of fetching commits + calling the model.
    await new Promise((resolve) => setTimeout(resolve, DUMMY_DELAY_MS));

    const markdown = buildDummyMarkdown(payload);

    const { error: uploadError } = await admin.storage
      .from('release-notes')
      .upload(payload.storagePath, markdown, { contentType: 'text/markdown', upsert: true });
    if (uploadError) throw uploadError;

    const { error: updateError } = await admin
      .from('release_notes')
      .update({ status: 'draft', error_message: null })
      .eq('id', payload.releaseNoteId)
      .eq('user_id', userId);
    if (updateError) throw updateError;
  } catch (err) {
    console.error('Release note generation failed', err);
    await admin
      .from('release_notes')
      .update({ status: 'failed', error_message: String((err as Error)?.message ?? err) })
      .eq('id', payload.releaseNoteId)
      .eq('user_id', userId);
  }
}

Deno.serve(async (req) => {
  if (req.method !== 'POST') {
    return json({ error: 'Method not allowed' }, 405);
  }

  // Authenticate the caller (the user JWT forwarded by supabase.functions.invoke).
  const authHeader = req.headers.get('Authorization') ?? '';
  const userClient = createClient(SUPABASE_URL, ANON_KEY, {
    global: { headers: { Authorization: authHeader } }
  });
  const {
    data: { user }
  } = await userClient.auth.getUser();
  if (!user) {
    return json({ error: 'Unauthorized' }, 401);
  }

  let payload: GeneratePayload;
  try {
    payload = (await req.json()) as GeneratePayload;
  } catch {
    return json({ error: 'Invalid JSON body' }, 400);
  }

  if (!payload.releaseNoteId || !payload.storagePath) {
    return json({ error: 'Missing releaseNoteId or storagePath' }, 400);
  }

  // Ensure the note exists, belongs to the caller, and is awaiting generation.
  const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);
  const { data: note } = await admin
    .from('release_notes')
    .select('id, status')
    .eq('id', payload.releaseNoteId)
    .eq('user_id', user.id)
    .maybeSingle();

  if (!note) {
    return json({ error: 'Release note not found' }, 404);
  }
  if (note.status !== 'generating') {
    return json({ error: 'Release note is not awaiting generation' }, 409);
  }

  // Do the slow work after responding.
  EdgeRuntime.waitUntil(runGeneration(payload, user.id));

  return json({ accepted: true, releaseNoteId: payload.releaseNoteId }, 202);
});
